using ModemConfigurator.Views;
using Prism.Ioc;
using Prism.Navigation;
using Prism.Services;
using Xamarin.Forms;
using Xamarin.Forms.PlatformConfiguration;
using Xamarin.Forms.PlatformConfiguration.iOSSpecific;
using Prism.Common;

namespace ModemConfigurator.ViewModels
{
    public class LoadingPageViewModel : ViewModelBase
    {
        private IContainerRegistry _containerRegistry { get; }

        public LoadingPageViewModel(INavigationService navigationService, IPageDialogService pageDialogService, 
                                    Services.IModemSettings modemSettings, IContainerRegistry containerRegistry) 
            : base(navigationService, pageDialogService, modemSettings)
        {
            _containerRegistry = containerRegistry;
        }

        public override async void OnNavigatedTo(INavigationParameters parameters)
        {
            _containerRegistry.RegisterForNavigation<MainPage, MainPageViewModel>();
            _containerRegistry.RegisterForNavigation<ModemSettingsPage, ModemSettingsPageViewModel>();
            _containerRegistry.RegisterForNavigation<ErrorPage, ErrorPageViewModel>();

            _containerRegistry.RegisterAutoGeneratedViews();

            var result = await NavigationService.NavigateAsync("/MainPage/NavigationPage/ModemSettingsPage");
            if (!result.Success)
            {
                await NavigationService.NavigateAsync("/ErrorPage", new NavigationParameters { { "exception", result.Exception } });
            }
        }
    }
}
